;;;
;;; -*- mode: scheme; coding: utf-8 -*-
;;; Test hpdf
;;;

(use gauche.test)
(use binary.pack)
(use file.util)

(test-start "hpdf")
(use hpdf)
(test-module 'hpdf)

(test-section "hpdf font")

(define (test-hpdf-load-ttf-font-from-file file flag)
  (let ((pdf (hpdf-new)))
    (if (file-is-readable? file)
        (hpdf-load-ttf-font-from-file pdf file flag)
        #f)))

;; test for non hpdf-use-jp-fonts
(define (test-hpdf-load-ttf-font-from-file2 file index flag)
  (let* ((pdf (hpdf-new))
         (null (hpdf-use-jp-encodings pdf)))
    (if (file-is-readable? file)
        (hpdf-load-ttf-font-from-file2 pdf file index flag)
        #f)))

(test* "ipag.ttf embed" "IPAGothic" (test-hpdf-load-ttf-font-from-file "font/ipag.ttf" #t))
(test* "ipag.ttf non-embed" "IPAGothic" (test-hpdf-load-ttf-font-from-file "font/ipag.ttf" #f))
(test* "ipagp.ttf embed" "IPAPGothic" (test-hpdf-load-ttf-font-from-file "font/ipagp.ttf" #t))
(test* "ipagp.ttf non-embed" "IPAPGothic" (test-hpdf-load-ttf-font-from-file "font/ipagp.ttf" #f))
(test* "ipagui.ttf embed" "IPAUIGothic" (test-hpdf-load-ttf-font-from-file "font/ipagui.ttf" #t))
(test* "ipagui.ttf non-embed" "IPAUIGothic" (test-hpdf-load-ttf-font-from-file "font/ipagui.ttf" #f))
(test* "ipam.ttf embed" "IPAMincho" (test-hpdf-load-ttf-font-from-file "font/ipam.ttf" #t))
(test* "ipam.ttf non-embed" "IPAMincho" (test-hpdf-load-ttf-font-from-file "font/ipam.ttf" #f))
(test* "ipamp.ttf embed" "IPAPMincho" (test-hpdf-load-ttf-font-from-file "font/ipamp.ttf" #t))
(test* "ipamp.ttf non-embed" "IPAPMincho" (test-hpdf-load-ttf-font-from-file "font/ipamp.ttf" #f))


(test-section "hpdf fonts")
(test* "jp fonts" HPDF_OK (hpdf-use-jp-fonts (hpdf-new)))
(test* "kr fonts" HPDF_OK (hpdf-use-kr-fonts (hpdf-new)))
(test* "cns fonts" HPDF_OK (hpdf-use-cns-fonts (hpdf-new)))
(test* "cnt fonts" HPDF_OK (hpdf-use-cnt-fonts (hpdf-new)))

(test-section "hpdf encodings")
(test* "jp encodings" HPDF_OK (hpdf-use-jp-encodings (hpdf-new)))
(test* "kr encodings" HPDF_OK (hpdf-use-kr-encodings (hpdf-new)))
(test* "cnt encodings" HPDF_OK (hpdf-use-cnt-encodings (hpdf-new)))
(test* "cns encodings" HPDF_OK (hpdf-use-cns-encodings (hpdf-new)))

(test-section "MS- fonts")
(test* "msgothic.ttc non-embed" "MS-Gothic" (test-hpdf-load-ttf-font-from-file2 "font/msgothic.ttc" 0 #f))
(test* "msgothic.ttc non-embed" "MS-PGothic" (test-hpdf-load-ttf-font-from-file2 "font/msgothic.ttc" 1 #f))
(test* "msgothic.ttc non-embed" "MS-UIGothic" (test-hpdf-load-ttf-font-from-file2 "font/msgothic.ttc" 2 #f))
(test* "msgoth04.ttc(JIS2004) non-embed" "MS-Gothic" (test-hpdf-load-ttf-font-from-file2 "font/msgoth04.ttc" 0 #f))
(test* "msgoth04.ttc(JIS2004) non-embed" "MS-PGothic" (test-hpdf-load-ttf-font-from-file2 "font/msgoth04.ttc" 1 #f))
(test* "msgoth04.ttc(JIS2004) non-embed" "MS-UIGothic" (test-hpdf-load-ttf-font-from-file2 "font/msgoth04.ttc" 2 #f))

(test* "msmincho.ttc index 0 non-embed" "MS-Mincho" (test-hpdf-load-ttf-font-from-file2 "font/msmincho.ttc" 0 #f))
(test* "msmincho.ttc index 1 non-embed" "MS-PMincho" (test-hpdf-load-ttf-font-from-file2 "font/msmincho.ttc" 1 #f))
(test* "msgoth04.ttc(JIS2004) index 0 non-embed" "MS-Mincho" (test-hpdf-load-ttf-font-from-file2 "font/msmin04.ttc" 0 #f))
(test* "msgoth04.ttc(JIS2004) index 1 non-embed" "MS-PMincho" (test-hpdf-load-ttf-font-from-file2 "font/msmin04.ttc" 1 #f))

(test-section "IPA fonts")
(test* "IPAGothic embed" "IPAGothic" (test-hpdf-load-ttf-font-from-file "font/ipag.ttf" #t))
(test* "IPAPGothic embed" "IPAPGothic" (test-hpdf-load-ttf-font-from-file "font/ipagp.ttf" #t))
(test* "IPAUIGothic embed" "IPAUIGothic" (test-hpdf-load-ttf-font-from-file "font/ipagui.ttf" #t))
(test* "IPAMincho embed" "IPAMincho" (test-hpdf-load-ttf-font-from-file "font/ipam.ttf" #t))
(test* "IPAPMincho embed" "IPAPMincho" (test-hpdf-load-ttf-font-from-file "font/ipamp.ttf" #t))

(test-section "mikachan fonts")
(test* "mikachanALL.ttc index 0 embed" "mikachan" (test-hpdf-load-ttf-font-from-file2 "font/mikachanALL.ttc" 0 #t))
(test* "mikachanALL.ttc index 1 embed" "mikachan-P" (test-hpdf-load-ttf-font-from-file2 "font/mikachanALL.ttc" 1 #t))
(test* "mikachanALL.ttc index 2 embed" "mikachan-PB" (test-hpdf-load-ttf-font-from-file2 "font/mikachanALL.ttc" 2 #t))
(test* "mikachanALL.ttc index 3 embed" "mikachan-PS" (test-hpdf-load-ttf-font-from-file2 "font/mikachanALL.ttc" 3 #t))

(test* "mikachan_puchi.ttc index 0 embed" "mikachan-puchi" (test-hpdf-load-ttf-font-from-file2 "font/mikachan_puchi.ttc" 0 #t))
(test* "mikachan_puchi.ttc index 1 embed" "mikachan-puchiB" (test-hpdf-load-ttf-font-from-file2 "font/mikachan_puchi.ttc" 1 #t))

(test-section "konatu fonts")
(test* "hpdf-load-ttf-font-from-file konatu.ttf embed" "Konatu" (test-hpdf-load-ttf-font-from-file "font/Konatu.ttf" #t))
(test* "hpdf-load-ttf-font-from-file konatu.ttf embed" "KonatuTohaba" (test-hpdf-load-ttf-font-from-file "font/KonatuTohaba.ttf" #t))


(test-section "type-lab fonts")
(test* "hpdf-load-ttf-font-from-file September L proportional embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/september-l-p.ttf" #t))
(test* "September L monospace embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/september-l-mono.ttf" #t))
(test* "September M proportional embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/september-m-p.ttf" #t))
(test* "September M monospace embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/september-m-mono.ttf" #t))
(test* "Anito Inline embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/anitoinline-p.ttf" #t))
(test* "Anito L proportional embed" "Anito-L-kyohkan" (test-hpdf-load-ttf-font-from-file "font/anito-l-p.ttf" #t))
(test* "Anito L monospace embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/anito-l-mono.ttf" #t))
(test* "hpdf-load-ttf-font-from-file Anito M proportional embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/anito-m-p.ttf" #t))
(test* "hpdf-load-ttf-font-from-file Anito M monospace embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/anito-m-mono.ttf" #t))
(test* "hpdf-load-ttf-font-from-file Anito Relief embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/anito-relief.ttf" #t))
(test* "hpdf-load-ttf-font-from-file Arare monospace embed" "Aralet-Mono-Kyohkan,Mono-Kyohkan" (test-hpdf-load-ttf-font-from-file "font/arare-mono.ttf" #t))
(test* "hpdf-load-ttf-font-from-file Arare proportional embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/arare-p.ttf" #t))
(test* "hpdf-load-ttf-font-from-file elegant w3 embed" "ElgseionW3.TTF" (test-hpdf-load-ttf-font-from-file "font/elegant-w3.ttf" #t))
(test* "hpdf-load-ttf-font-from-file elegant w5 embed" "ElgseionW5.TTF" (test-hpdf-load-ttf-font-from-file "font/elegant-w5.ttf" #t))
(test* "hpdf-load-ttf-font-from-file elegant w7 embed" "ElgseionW7.TTF" (test-hpdf-load-ttf-font-from-file "font/elegant-w7.ttf" #t))
(test* "hpdf-load-ttf-font-from-file elegant w9 embed" "ElgseionW9.TTF" (test-hpdf-load-ttf-font-from-file "font/elegant-w9.ttf" #t))

(test-section "Aqua fonts")
(test* "hpdf-load-ttf-font-from-file aquafont embed" "aquafont" (test-hpdf-load-ttf-font-from-file "font/aquafont.ttf" #t))
(test* "hpdf-load-ttf-font-from-file aqua_pfont embed" "aqua_pfont" (test-hpdf-load-ttf-font-from-file "font/aqua_pfont.ttf" #t))

(test-section "Sana fonts")
(test* "hpdf-load-ttf-font-from-file SNsanafon embed" "SanaFon" (test-hpdf-load-ttf-font-from-file "font/SNsanafon.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonGyou embed" "SanafonGyou" (test-hpdf-load-ttf-font-from-file "font/SNsanafonGyou.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonKazari embed" "SanafonKazari" (test-hpdf-load-ttf-font-from-file "font/SNsanafonKazari.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonMugi embed" "SanafonMugi" (test-hpdf-load-ttf-font-from-file "font/SNsanafonMugi.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonObi embed" "SNsanafonObi" (test-hpdf-load-ttf-font-from-file "font/SNsanafonObi.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonkaku embed" "SanaFonKaku" (test-hpdf-load-ttf-font-from-file "font/SNsanafonkaku.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonkakuP embed" "SanafonkakuP" (test-hpdf-load-ttf-font-from-file "font/SNsanafonkakuP.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonmaru embed" "SanaFonMaru" (test-hpdf-load-ttf-font-from-file "font/SNsanafonmaru.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonmaruP embed" "SanafonMaruP" (test-hpdf-load-ttf-font-from-file "font/SNsanafonmaruP.ttf" #t))
(test* "hpdf-load-ttf-font-from-file SNsanafonu embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/SNsanafonu.ttf" #t))

(test-section "XANO fonts")
(test* "Kandata embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/Kandata.ttf" #t))
(test* "QANO mincho embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/QANO-mincho.ttf" #t))
(test* "QuiMi mincho embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/QuiMi-mincho.ttf" #t))
(test* "XANO-mincho embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/XANO-mincho.ttf" #t))
(test* "XANO-mincho-U32 embed" "XANO-mincho-U32" (test-hpdf-load-ttf-font-from-file "font/XANO-mincho-U32.ttf" #t))

(test-section "Other fonts")
(test* "akubin embed" "unsupported" (test-hpdf-load-ttf-font-from-file "font/akubin.ttf" #t))
(test* "cinecaption embed" "cinecaption" (test-hpdf-load-ttf-font-from-file "font/cinecaption226.ttf" #t))
(test* "elmer monospace embed" "ElmerFont" (test-hpdf-load-ttf-font-from-file "font/elmer.ttf" #t))
(test* "elmer proportional embed" "ElmerPFont" (test-hpdf-load-ttf-font-from-file "font/elmerp.ttf" #t))

(test-section "hpdf text")
(let* ((pdf (hpdf-new))
       (s (hpdf-set-compression-mode pdf HPDF_COMP_ALL))
       (s (hpdf-use-jp-encodings pdf))
       (s (hpdf-use-jp-fonts pdf))
       ;;(font_name (hpdf-load-ttf-font-from-file2 pdf "font/msgothic.ttc" 2 #f))
       ;;(font_name (hpdf-load-ttf-font-from-file pdf "font/ipagui.ttf" #f))
       ;;(font_name (hpdf-load-ttf-font-from-file2 pdf "font/msgothic.ttc" 2 #t))
       ;;(font_name (hpdf-load-ttf-font-from-file pdf "font/VL-Gothic-Regular.ttf" #t))
       ;;(font_name (hpdf-load-ttf-font-from-file pdf "font/VL-PGothic-Regular.ttf" #t))
       ;;(font_name (hpdf-load-ttf-font-from-file pdf "font/Konatu.ttf" #t))
       ;;(font_name (hpdf-load-ttf-font-from-file pdf "font/KonatuTohaba.ttf" #t))
       ;;(font_name (hpdf-load-ttf-font-from-file2 pdf "font/mikachanALL.ttc" 0 #t))
       ;;(font_name (hpdf-load-ttf-font-from-file2 pdf "font/mikachanALL.ttc" 1 #t))
       ;;(font_name (hpdf-load-ttf-font-from-file2 pdf "font/mikachanALL.ttc" 2 #t))
       (font_name (hpdf-load-ttf-font-from-file2 pdf "font/mikachanALL.ttc" 3 #t))
       ;;(font_name (hpdf-load-ttf-font-from-file pdf "font/CapaMMO.TTF" #f))
       ;;(font (hpdf-get-font pdf font_name "90ms-RKSJ-H"))
       ;;(font (hpdf-get-font pdf "MS-UIGothic" "90ms-RKSJ-H"))
       (font (hpdf-get-font pdf font_name "90ms-RKSJ-H"))
       (null (hpdf-set-page-mode pdf HPDF_PAGE_MODE_USE_OUTLINE))

       (page_1 (hpdf-add-page pdf))

       (root (hpdf-create-outline pdf #f "JP font demo" #f))
       (null (hpdf-outline-set-opened root #t))
       (outline (hpdf-create-outline pdf root "MS-UIGothic" #f))
       (dst (hpdf-page-create-destination page_1))
       (null (hpdf-outline-set-destination outline dst))

       (font (hpdf-page-set-font-and-size page_1 font 14))
       (st (hpdf-page-begin-text page_1))
       (s (read-line (open-input-file "data/sjis.txt") #t))
       (dummy (hpdf-page-show-text page_1 s))
       (dummy (hpdf-page-end-text page_1))
       )
  (hpdf-save-to-file pdf "data/budori.pdf"))

;; epilogue
(test-end)

