;;;
;;; -*- mode: scheme; coding: utf-8 -*-
;;; Test hpdf
;;;

(use gauche.test)
(use gauche.charconv)
(use binary.pack)
(use file.util)

(test-start "hpdf")
(use hpdf)
(test-module 'hpdf)

(define (test-subsection msg)
  (format #t "~a()\n" msg))


(test-section "hpdf image")
(define (test-hpdf-load-png-image-from-file filename)
  (let* ((pdf (hpdf-new)))
    (hpdf-load-png-image-from-file pdf filename)))

(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI0G01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI0G01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI0G02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI4A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI4A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI6A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASI6A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN0G01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN0G02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN4A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN4A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN6A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BASN6A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGAI4A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGAI4A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGAN6A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGAN6A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGBN4A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGGN4A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGWN6A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/BGYN6A16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CCWN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CCWN3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CDFN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CDHN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CDSN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CDUN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CH1N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CH2N3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CM0N0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CM7N0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CM9N0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CS3N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CS3N3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CS5N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CS5N3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CS8N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CS8N3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CT0N0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CT1N0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/CTZN0G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F00N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F00N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F01N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F01N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F02N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F02N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F03N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F03N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F04N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/F04N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G03N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G03N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G03N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G04N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G04N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G04N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G05N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G05N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G05N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G07N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G07N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G07N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G10N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G10N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G10N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G25N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G25N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/G25N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI1N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI1N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI2N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI2N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI4N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI4N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI9N0G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/OI9N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PNGSUITE.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PP0N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PP0N6A08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PS1N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PS1N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PS2N0G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/PS2N2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S01I3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S01N3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S02I3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S02N3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S03I3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S03N3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S04I3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S04N3P01.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S05I3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S05N3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S06I3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S06N3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S07I3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S07N3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S08I3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S08N3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S09I3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S09N3P02.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S32I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S32N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S33I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S33N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S34I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S34N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S35I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S35N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S36I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S36N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S37I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S37N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S38I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S38N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S39I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S39N3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S40I3P04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/S40N3P04.PNG")))
(test* "TBBN1G04.PNG" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBBN1G04.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBBN2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBBN3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBGN2C16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBGN3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBRN2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBWN1G16.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBWN3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TBYN3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TP0N1G08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TP0N2C08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TP0N3P08.PNG")))
(test* "" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/TP1N3P08.PNG")))
;; SEGV
;; (test* "X00N0G01.PNG" *test-error* (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/X00N0G01.PNG")))
(test* "XCRN0G04.PNG" *test-error* (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/XCRN0G04.PNG")))
(test* "XLFN0G04.PNG" *test-error* (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/XLFN0G04.PNG")))
(test* "Z00N2C08.PNG" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/Z00N2C08.PNG")))
(test* "Z03N2C08.PNG" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/Z03N2C08.PNG")))
(test* "Z06N2C08.PNG" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/Z06N2C08.PNG")))
(test* "Z09N2C08.PNG" <hpdf-image> (class-of (test-hpdf-load-png-image-from-file "image/PngSuite/Z09N2C08.PNG")))

;; epilogue
(test-end)
