language: c
notifications:
  recipients:
    - kenhys@gmail.com
install:
  - sudo apt-get install -y autotools-dev intltool
  - wget http://prdownloads.sourceforge.net/gauche/Gauche-0.9.3.3.tgz
  - tar zxvf Gauche-0.9.3.3.tgz
  - (cd Gauche-0.9.3.3; sh ./configure; make; sudo make install)
  - git clone git://github.com/libharu/libharu.git
  - (cd libharu; sh buildconf.sh --force; sh configure; make; sudo make install)
before_script:
  - sh ./DIST gen
  - ./configure --with-zlib=/usr --with-png=/usr --with-hpdf=/usr/local
  - make
script:
  - test/run-test.sh
